name:                cac
version:             0.1.0.0
github:              "Mike/cac"
license:             BSD3
author:              "Mike"
maintainer:          "michaelmossey@gmail.com"
copyright:           "2017"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            programming

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Mike/cac#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cac-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cac

tests:
  cac-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cac
